import type { CaseQuestion, CourtCase, IdealJudgment } from "./case-library";

/**
 * A compact, clinician-editable seed list.  The builder below expands each
 * scenario into six language bands, so the game always has exactly thirty
 * cases available for P.1–P.6 while keeping the facts and fair decision
 * internally consistent.
 */
type Seed = {
  title: string;
  summary: string;
  item: string;
  place: string;
  time: string;
  complainant: string;
  respondent: string;
  allegation: string;
  reason: string;
  defenceAction: string;
  outcome: string;
  targetWord: string;
  targetMeaning: string;
  idealFinding: IdealJudgment["finding"];
  idealPunishment: IdealJudgment["punishment"];
  idealSeverity: IdealJudgment["severity"];
  idealReasoning: string;
};

const seeds: Seed[] = [
  {
    title: "借出的平板電腦",
    summary: "學校平板在小息後出現裂痕，借用學生和老師對損壞時間各有說法。",
    item: "銀色平板電腦",
    place: "三年級課室的充電櫃",
    time: "星期二午膳後",
    complainant: "班主任 林老師",
    respondent: "學生 嘉怡",
    allegation: "她把平板放在桌邊，令平板跌下而損壞",
    reason: "她急着把平板交回充電櫃，沒有留意桌邊仍有水樽",
    defenceAction: "她看見裂痕後立即通知老師，並把平板放回有軟墊的格子",
    outcome: "平板仍可開機，但屏幕右下角需要更換",
    targetWord: "裂痕",
    targetMeaning: "物件表面出現的細小裂縫",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "平板確實在嘉怡使用後出現裂痕，但充電櫃附近有水樽且沒有固定放置位置。她即時報告，較適合提醒雙方改善保管方法。",
  },
  {
    title: "公園單車相撞",
    summary: "兩架單車在公園彎位相撞，兩名騎車者對誰先進入彎位有不同記憶。",
    item: "紅色兒童單車",
    place: "海濱公園的木橋彎位",
    time: "星期六下午四時",
    complainant: "騎車者 梁先生",
    respondent: "騎車者 子朗",
    allegation: "他在彎位加速，沒有讓路給迎面的單車",
    reason: "他以為前方沒有其他人，想趕在公園關閉前回到入口",
    defenceAction: "他撞車後停下，協助檢查對方膝蓋，並致電公園職員",
    outcome: "兩架單車的車鈴損壞，沒有人需要送院",
    targetWord: "迎面",
    targetMeaning: "從正前方而來",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "彎位視線受木欄遮擋，兩人都沒有先減速；子朗事後停下協助。以安全警告和重溫公園單車規則最合比例。",
  },
  {
    title: "圖書館的水漬",
    summary: "一本故事書歸還時有水漬，圖書館和借閱者對水漬何時形成未能完全證實。",
    item: "《海底探險》故事書",
    place: "公共圖書館的兒童閱覽室",
    time: "借書後第七天的下午",
    complainant: "圖書館員 郭小姐",
    respondent: "借閱者 宇軒",
    allegation: "他把未蓋好的水樽放在書旁，令書頁沾濕",
    reason: "他在窗邊閱讀時把水樽放在書袋外，移動書袋時水樽倒下",
    defenceAction: "他發現書頁濕了便拍照，歸還時主動告訴館員",
    outcome: "封面完整，只有中間數頁留下淡淡水印",
    targetWord: "沾濕",
    targetMeaning: "被水弄到而變濕",
    idealFinding: "insufficient",
    idealPunishment: "none",
    idealSeverity: 0,
    idealReasoning: "借出檢查沒有記錄內頁狀況，照片也看不清水印是否原有。宇軒主動報告，現有證據不足以要求賠償。",
  },
  {
    title: "校隊球衣去向",
    summary: "比賽後少了一件校隊球衣，隊員和教練對收拾衣物的次序有不同說法。",
    item: "印有 7 號的藍色球衣",
    place: "學校體育館的長椅",
    time: "校際籃球比賽結束後",
    complainant: "教練 陳先生",
    respondent: "隊員 文俊",
    allegation: "他把球衣帶離體育館而沒有交回",
    reason: "他以為球衣是自己的備用衣，匆忙收拾時沒有查看號碼",
    defenceAction: "他回家發現號碼不對，第二天把球衣洗好並交回教練",
    outcome: "球衣沒有遺失，只有洗衣後仍留有泥點",
    targetWord: "備用",
    targetMeaning: "預先準備、需要時可替代使用",
    idealFinding: "not-guilty",
    idealPunishment: "none",
    idealSeverity: 0,
    idealReasoning: "球衣外觀相同而號碼容易被忽略，文俊第二天即歸還，較像疏忽拿錯而非故意帶走。",
  },
  {
    title: "麵包店的找續",
    summary: "顧客指店員少找十元，店員指顧客在繁忙時自行把硬幣放錯位置。",
    item: "十元硬幣",
    place: "街角麵包店的收銀櫃枱",
    time: "星期五放學後",
    complainant: "顧客 何女士",
    respondent: "店員 阿明",
    allegation: "他收款後少找了十元",
    reason: "當時有三位顧客同時排隊，找續紙條被另一張訂單遮住",
    defenceAction: "他查看收銀紀錄，發現櫃枱下有一枚未交出的十元硬幣",
    outcome: "收銀總額比系統預期多十元，但沒有錄影收銀員的手部動作",
    targetWord: "遮住",
    targetMeaning: "把某物蓋着，使人看不見",
    idealFinding: "insufficient",
    idealPunishment: "none",
    idealSeverity: 0,
    idealReasoning: "收銀總額多出十元支持兩種可能，現場又沒有清楚錄影。沒有足夠資料證明是店員故意或疏忽少找。",
  },
  {
    title: "巴士上的雨傘",
    summary: "乘客把相似雨傘帶下巴士，司機和乘客對雨傘在座位上的位置有不同記憶。",
    item: "有黃色掛繩的黑色雨傘",
    place: "往沙田方向的巴士上層",
    time: "暴雨天的傍晚",
    complainant: "乘客 周太",
    respondent: "乘客 偉倫",
    allegation: "他拿走了周太放在座位旁的雨傘",
    reason: "兩把雨傘都有黃色掛繩，他下車時以為靠近自己的那把就是他的",
    defenceAction: "他回到家發現傘柄有姓名貼紙，立即致電巴士公司並在翌日送回",
    outcome: "巴士閉路電視只能拍到兩人同時下車，未能看清傘柄",
    targetWord: "相似",
    targetMeaning: "外表或特徵很接近",
    idealFinding: "not-guilty",
    idealPunishment: "none",
    idealSeverity: 0,
    idealReasoning: "兩把雨傘外觀相似，偉倫發現後立即尋找失主並歸還。證據較支持無意拿錯。",
  },
  {
    title: "社區花圃的水喉",
    summary: "公共花圃的水喉被移到另一位置，義工和管理員對誰應先通知大家有爭議。",
    item: "綠色澆水水喉",
    place: "屋苑中央花圃",
    time: "星期日清晨",
    complainant: "管理員 蘇先生",
    respondent: "義工 嘉文",
    allegation: "他擅自移動水喉，令花圃一度沒有水可用",
    reason: "原來的位置漏水，他想先把水喉放到沒有泥沙的水龍頭",
    defenceAction: "他留下紙條說明位置，並用自己的膠帶暫時修補漏水處",
    outcome: "花圃只有兩盆幼苗因缺水而變軟，翌日已恢復",
    targetWord: "暫時",
    targetMeaning: "在短時間內、不是永久地",
    idealFinding: "shared",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "移動水喉有修理漏水的合理原因，但沒有先通知管理員，令幼苗受影響。分擔實際損失並訂立通知方法較合適。",
  },
  {
    title: "運動會的相機",
    summary: "學校相機在運動會後鏡頭刮花，攝影隊和器材員對相機最後由誰保管各有記憶。",
    item: "黑色校用相機",
    place: "田徑場旁的器材帳篷",
    time: "運動會閉幕前後",
    complainant: "器材員 黃老師",
    respondent: "學生攝影員 凱晴",
    allegation: "她把相機放在沒有保護套的地上，令鏡頭被刮花",
    reason: "她要同時拍攝頒獎禮和搬動腳架，先把相機放在帳篷邊",
    defenceAction: "她發現鏡頭異常後立刻停止使用，並把記憶卡交給老師保存",
    outcome: "刮痕只在濾鏡上，主鏡頭仍然可以拍攝",
    targetWord: "保護套",
    targetMeaning: "用來包住和保護物件的套子",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "凱晴短暫把相機放在帳篷邊是不夠小心，但器材員沒有提供固定收納位置。相機仍可使用，安全提醒比罰款合比例。",
  },
  {
    title: "二手玩具的電池",
    summary: "網上交易的機械人玩具不能開動，買家和賣家對電池是否已說明未能完全對上。",
    item: "藍色機械人玩具",
    place: "社區中心的交收桌",
    time: "星期三放學後",
    complainant: "買家 皓謙",
    respondent: "賣家 佩雯",
    allegation: "她把不能使用的玩具當作正常貨品出售",
    reason: "她以為玩具只是沒有裝電池，沒有在交收時測試",
    defenceAction: "她回家找到原裝電池，發現玩具能動，便把電池和測試影片傳給買家",
    outcome: "交易訊息只寫着「二手、外觀良好」，沒有寫明是否附電池",
    targetWord: "交收",
    targetMeaning: "買賣雙方當面交付物品和款項",
    idealFinding: "shared",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "賣家沒有清楚說明不附電池，買家也沒有在交收時要求測試。退回部分款項或補送電池能公平處理。",
  },
  {
    title: "義賣箱的數目",
    summary: "義賣後的捐款比登記估算少，學生和老師對點算過程中的封箱時間有不同紀錄。",
    item: "封好的捐款箱",
    place: "學校禮堂後台",
    time: "慈善義賣結束後",
    complainant: "籌款老師 趙老師",
    respondent: "學生幹事 俊熙",
    allegation: "他在保管捐款箱時沒有依照程序，造成金額差異",
    reason: "後台突然停電，他把捐款箱移到有燈的房間，沒有即時找老師簽收",
    defenceAction: "他把箱子交回時封條完整，並在紀錄表寫下移動時間和見證人",
    outcome: "估算金額只是按人數和平均捐款推算，沒有逐筆收據",
    targetWord: "估算",
    targetMeaning: "根據已有資料大約計算",
    idealFinding: "insufficient",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "金額本來就是估算，封條完整且有移動紀錄，不能推定有人取走款項。應提醒遵守交接程序並改善點算方法。",
  },
  {
    title: "課室模型的零件",
    summary: "小組模型少了一個齒輪，組員對整理桌面時誰把零件放進盒子有爭議。",
    item: "透明塑膠齒輪",
    place: "四年級課室的科學桌",
    time: "科學課展示前一天",
    complainant: "組員 子軒",
    respondent: "組員 雅文",
    allegation: "她把齒輪當作垃圾丟掉，令小組不能完成模型",
    reason: "齒輪混在剪紙碎片中，她清理桌面時以為那是廢料",
    defenceAction: "她回到垃圾桶尋找，並用紙板做出臨時替代件",
    outcome: "模型仍能運作，但齒輪的轉速比原來慢",
    targetWord: "替代",
    targetMeaning: "用另一件相近的東西代替原來的",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "零件混在紙屑中容易被誤認，雅文清理前也應先問組員；她主動補救。以提醒和共同整理規則處理較合適。",
  },
  {
    title: "外賣餐盒的標籤",
    summary: "餐廳把含有花生的餐盒交給過敏顧客，店員和送餐員對標籤何時脫落有不同說法。",
    item: "貼有紅色過敏標籤的餐盒",
    place: "商場美食廣場的取餐架",
    time: "星期六中午繁忙時段",
    complainant: "顧客 梁小姐",
    respondent: "餐廳店員 偉成",
    allegation: "他沒有核對餐盒標籤，令錯誤餐點交到顧客手上",
    reason: "取餐架上同時有兩張相似姓氏的訂單，紅色標籤被紙袋邊遮住",
    defenceAction: "他得知後立即通知顧客不要進食，並重新製作沒有花生的餐點",
    outcome: "顧客沒有出現嚴重反應，但需要到保健室觀察",
    targetWord: "核對",
    targetMeaning: "逐項比較，確認資料是否一致",
    idealFinding: "guilty",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "過敏資料屬重要安全訊息，店員應在交付前核對；他及時阻止顧客進食並補救，賠償直接醫療費比嚴厲處分相稱。",
  },
  {
    title: "公共充電器的電線",
    summary: "社區共享充電櫃的電線被拔出，使用者和管理員對是否有人絆倒有不同記錄。",
    item: "白色充電電線",
    place: "青年中心的共享充電櫃",
    time: "星期一晚上",
    complainant: "中心職員 何先生",
    respondent: "使用者 昊霖",
    allegation: "他拔出別人的電線並把電線留在通道上",
    reason: "他的手機顯示過熱，他想先拔掉旁邊插座的電線散熱",
    defenceAction: "他把電線捲好放回櫃內，並在值班簿寫下插座過熱",
    outcome: "沒有物品損壞，但一名訪客差點被電線絆倒",
    targetWord: "散熱",
    targetMeaning: "把熱力散開，令溫度降低",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "拔線有安全考慮，但放在通道會造成絆倒危險；他最後收好並報告問題。提醒正確處理和檢查充電櫃較合比例。",
  },
  {
    title: "街市秤重爭議",
    summary: "顧客認為蔬菜重量不足，檔主指膠袋和秤的讀數造成誤會。",
    item: "一袋本地菜心",
    place: "街市蔬菜檔的電子磅",
    time: "星期日早上",
    complainant: "顧客 鄭太",
    respondent: "檔主 鍾先生",
    allegation: "他按較高重量收款，卻給了較少蔬菜",
    reason: "秤上先放了濕膠袋，讀數沒有在放菜前歸零",
    defenceAction: "他重新把膠袋重量扣除，並提出退回差額",
    outcome: "檔口沒有保存當時的磅重照片，只有顧客和檔主的回憶",
    targetWord: "歸零",
    targetMeaning: "把儀器的讀數調回零點",
    idealFinding: "guilty",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "檔主承認沒有先把膠袋重量歸零，收款因此可能偏高；他願意退回差額，應以補償及正確使用電子磅處理。",
  },
  {
    title: "校巴的預留座位",
    summary: "校巴上的預留座位被其他學生坐上，學生和司機對座位牌是否清楚有爭議。",
    item: "貼有輪椅圖案的前排座位",
    place: "學校接送巴士的第一排",
    time: "放學下雨時",
    complainant: "學生家長 余太",
    respondent: "學生 柏翰",
    allegation: "他看見座位牌仍坐上預留座位，令需要座位的同學沒有位置",
    reason: "座位牌被雨傘袋遮住，他以為只是普通空位",
    defenceAction: "司機提醒後他立即起身，並協助把書包移到行李架",
    outcome: "需要座位的學生最後順利坐下，車程只延誤兩分鐘",
    targetWord: "預留",
    targetMeaning: "預先保留給特定的人或用途",
    idealFinding: "not-guilty",
    idealPunishment: "none",
    idealSeverity: 0,
    idealReasoning: "座位牌被雨傘袋遮住，柏翰被提醒後立即讓座。事件較像標示不清造成的誤會，不宜處分學生。",
  },
  {
    title: "社區壁畫的顏色",
    summary: "壁畫完成後出現一塊不同色區，設計小組和義工對誰更改顏料比例有爭議。",
    item: "海浪形的藍色顏料",
    place: "社區中心外牆壁畫",
    time: "最後一次上色的下午",
    complainant: "設計師 方小姐",
    respondent: "義工 小傑",
    allegation: "他沒有依照配方加入白色顏料，令海浪顏色變深",
    reason: "原來的量杯被拿去清洗，他用普通杯估算比例",
    defenceAction: "他把剩餘顏料封好，拍下比例並請設計師決定是否重新上色",
    outcome: "深色區域可以融入陰影，但與原設計稿不完全相同",
    targetWord: "比例",
    targetMeaning: "不同數量之間的相對關係",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "小傑沒有使用指定量杯，但工具不足也未獲及時補充；深色可作陰影，較適合記錄改動和提醒核對比例。",
  },
  {
    title: "海濱相機的照片",
    summary: "一部借來的相機在海濱拍攝後找不到，借用者和同行朋友對最後一次使用位置有分歧。",
    item: "有藍色相機帶的數碼相機",
    place: "西九海濱的觀景台",
    time: "夕陽落山前十分鐘",
    complainant: "相機主人 晴晴",
    respondent: "借用者 家朗",
    allegation: "他把相機留在觀景台欄杆上，令相機被人拿走",
    reason: "他要扶住被風吹起的相片，暫時把相機放在欄杆旁",
    defenceAction: "他沿原路尋找，向保安交出失物登記，並提供最後一張照片時間",
    outcome: "照片時間只顯示相機曾在觀景台，沒有拍到離開後的情況",
    targetWord: "暫時",
    targetMeaning: "短時間內，不是長久地",
    idealFinding: "shared",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "家朗把相機放在沒有看管的位置是不夠小心，但他立刻搜尋並報失；按實際遺失責任分擔補償較公平。",
  },
  {
    title: "動物義工的餵食表",
    summary: "收容中心的兩隻貓在不同時間得到餵食，義工和主管對表格更新是否清楚有爭議。",
    item: "標有橙色爪印的餵食盒",
    place: "動物收容中心的貓舍",
    time: "週末早上的交更時段",
    complainant: "中心主管 潘女士",
    respondent: "義工 子謙",
    allegation: "他沒有按照餵食表，令其中一隻貓重複進食",
    reason: "前一位義工把完成記號寫在錯誤一行，他以為另一隻貓仍未吃飯",
    defenceAction: "他發現後立即通知主管，並量度兩隻貓的食量和精神狀況",
    outcome: "兩隻貓沒有生病，但其中一隻當天少吃了晚餐",
    targetWord: "交更",
    targetMeaning: "把工作和資料交給下一位負責的人",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "餵食表有錯誤記號，交更時也沒有口頭核對；子謙主動觀察動物並報告。改善交接和提醒即可。",
  },
  {
    title: "露營食物的分配",
    summary: "露營隊伍少了一包應急糧食，隊長和隊員對誰在暴雨前打開背包有不同記憶。",
    item: "一包密封的應急餅乾",
    place: "大嶼山營地的公共食物箱",
    time: "暴雨警告發出後",
    complainant: "領隊 黃先生",
    respondent: "隊員 思穎",
    allegation: "她沒有登記便取走應急餅乾，令全隊的備糧不足",
    reason: "她看見年幼隊員肚餓，以為領隊已同意先分一包",
    defenceAction: "她把自己的一半晚餐分給大家，並在雨停後補寫取用紀錄",
    outcome: "隊伍仍有足夠食物，但第二天早餐選擇較少",
    targetWord: "應急",
    targetMeaning: "在突發或緊急情況下使用",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "思穎沒有先確認便取用應急糧，但動機是照顧年幼隊員，也有分食和補記錄。以提醒和重訂取用程序處理。",
  },
  {
    title: "科學展品的標籤",
    summary: "展覽中的火山模型標籤被換到另一座模型旁，兩組學生對換標籤的時間有爭議。",
    item: "寫有「小蘇打火山」的白色標籤",
    place: "學校科學展覽禮堂",
    time: "開放參觀前的早上",
    complainant: "參展組員 婷恩",
    respondent: "另一組組員 朗朗",
    allegation: "他把標籤移走，令觀眾誤以為另一組的模型用了相同方法",
    reason: "清潔桌面時，他把散落的標籤集中到同一個盒子，之後按模型大小重新放置",
    defenceAction: "他發現錯誤後立即通知兩組，並用膠紙標示兩座模型的邊界",
    outcome: "開幕前已更正，但部分觀眾看過錯誤標籤",
    targetWord: "散落",
    targetMeaning: "零散地分布在不同地方",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "朗朗整理標籤時沒有先核對所屬小組，展覽安排也沒有固定標籤位置；他及時更正，提醒和改善流程即可。",
  },
  {
    title: "天台盆栽的泥土",
    summary: "大廈天台的泥土掉到晾衣區，住戶和園藝義工對搬盆栽時是否有防護措施有分歧。",
    item: "裝有薄荷的白色盆栽",
    place: "大廈天台花園和晾衣區之間",
    time: "大風前的星期日下午",
    complainant: "住戶 馬太",
    respondent: "園藝義工 俊文",
    allegation: "他搬動盆栽時沒有墊好托盤，令泥土掉到別人的衣服上",
    reason: "他先把盆栽移到牆邊避風，原有托盤被水沖裂而不能使用",
    defenceAction: "他清理晾衣區並把衣物送到洗衣店，之後通知管理處更換托盤",
    outcome: "兩件白色校服留下淡褐色污跡，其中一件可以洗掉",
    targetWord: "防護",
    targetMeaning: "預先採取方法避免受到傷害或損失",
    idealFinding: "guilty",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "俊文有避風的合理目的，但搬動盆栽前仍應先安排防護；衣物確有污損，他已清理並協助送洗，補償實際費用較合適。",
  },
  {
    title: "借出的遊戲卡",
    summary: "珍藏遊戲卡歸還時有摺痕，借用者和卡主對卡片是否原已有痕跡各有說法。",
    item: "閃亮的龍騎士遊戲卡",
    place: "課室後排的閱讀角",
    time: "借出後第三天",
    complainant: "卡主 浩然",
    respondent: "借用者 恩晴",
    allegation: "她把遊戲卡放在沒有保護套的書包內，令卡片摺曲",
    reason: "她以為卡片已放進硬膠套，實際上只夾在作業簿中",
    defenceAction: "她發現摺痕後主動提出用自己的同款卡交換，並保留借還訊息",
    outcome: "借出前沒有拍照，摺痕只在卡片背面邊角",
    targetWord: "珍藏",
    targetMeaning: "值得保留和收藏的物品",
    idealFinding: "insufficient",
    idealPunishment: "none",
    idealSeverity: 0,
    idealReasoning: "沒有借出前照片，不能確定摺痕何時出現；恩晴提出補救，也沒有證據顯示她故意損壞。可提醒使用保護套。",
  },
  {
    title: "演出門票的座位",
    summary: "兩名觀眾拿到相同座位號碼的門票，售票員和觀眾對電子系統何時出錯未能確認。",
    item: "印有 B12 的音樂會門票",
    place: "社區劇院入口驗票處",
    time: "星期六晚上七時半",
    complainant: "觀眾 嘉樂",
    respondent: "售票員 欣怡",
    allegation: "她重複售出同一個座位，令觀眾要站在入口等待",
    reason: "網絡短暫中斷，付款頁面重複提交同一張訂單",
    defenceAction: "她核對付款時間和座位圖，安排其中一位觀眾到同價位的 B13",
    outcome: "兩位觀眾都能入場，但其中一人要坐在側邊位置",
    targetWord: "重複",
    targetMeaning: "同一件事再次出現或做多一次",
    idealFinding: "insufficient",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "系統中斷和重複提交都有可能，售票員未必能控制技術故障；觀眾被安排到同價位側邊，退回部分票價較公平。",
  },
  {
    title: "大廈走廊的噪音",
    summary: "住戶投訴深夜搬運家具，搬屋公司和住戶對大廈告示及實際時間有不同記錄。",
    item: "有橡膠墊的搬運車",
    place: "住宅大廈八樓走廊",
    time: "星期三晚上九時後",
    complainant: "住戶 梁太",
    respondent: "搬屋工人 何先生",
    allegation: "他在限制時間後推動搬運車，造成持續噪音",
    reason: "貨車只能在晚上到達，他要先把易碎物品移入單位避雨",
    defenceAction: "他得知投訴後停止搬運，改為翌日白天完成，並向住戶道歉",
    outcome: "走廊監控沒有錄音，只能確認搬運車在晚上出現",
    targetWord: "限制",
    targetMeaning: "規定不能超過的範圍或時間",
    idealFinding: "guilty",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "深夜搬運確實違反大廈安靜時段，但暴雨令搬運有實際需要；他收到提醒便停止。正式警告和預先申請時段較合比例。",
  },
  {
    title: "公共雨棚的位置",
    summary: "店舖外的可移動雨棚遮住送貨通道，店主和街坊對搬動雨棚是否先經同意有爭議。",
    item: "藍白相間的可移動雨棚",
    place: "巴士站旁的社區通道",
    time: "連續下雨的三天",
    complainant: "店主 葉女士",
    respondent: "街坊義工 偉杰",
    allegation: "他把雨棚移到店門前，令送貨車不能靠近",
    reason: "他想讓等候巴士的長者避雨，原來位置正被積水淹沒",
    defenceAction: "他在店門開門前把雨棚摺起，並留下聯絡紙條商量新位置",
    outcome: "送貨延遲一次，雨棚沒有永久損壞",
    targetWord: "摺起",
    targetMeaning: "把物件折疊起來以縮小體積",
    idealFinding: "shared",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "雨棚確實影響送貨，但移動是為了讓長者避開積水；雙方都可先聯絡和標示位置，按一次延誤的直接損失分擔較公平。",
  },
  {
    title: "單車泊位的鎖",
    summary: "共享單車被鎖在私人泊位，使用者和管理員對泊位標記是否看得清楚有不同說法。",
    item: "橙色共享單車",
    place: "屋苑地下單車停泊區",
    time: "星期一早上上班前",
    complainant: "管理員 蔡先生",
    respondent: "居民 健豪",
    allegation: "他把共享單車鎖在消防通道旁，阻礙其他人取車",
    reason: "共享泊位的地貼被雨水沖淡，他以為旁邊空位仍屬公共區域",
    defenceAction: "他收到通知後立即移車，並拍照報告地貼已褪色",
    outcome: "通道只被阻擋約二十分鐘，沒有影響消防設備",
    targetWord: "褪色",
    targetMeaning: "顏色變淡，不再鮮明",
    idealFinding: "not-guilty",
    idealPunishment: "none",
    idealSeverity: 0,
    idealReasoning: "泊位標記已褪色而容易誤解，健豪收到通知後立即移車，也沒有實際消防危險。應先修補標記而非處分居民。",
  },
  {
    title: "網上留言的截圖",
    summary: "班級群組出現一張被指嘲笑同學的截圖，發文者和被影射學生對原文語氣有不同理解。",
    item: "班級群組的對話截圖",
    place: "家長與學生共用的通訊群組",
    time: "考試成績公布當晚",
    complainant: "學生家長 林太",
    respondent: "學生 皓文",
    allegation: "他把同學的成績寫在群組，令同學感到羞辱",
    reason: "他想用表格提醒大家核對分數，沒有想到公開姓名會造成壓力",
    defenceAction: "他刪除訊息並私下道歉，老師要求他改用不顯示姓名的表格",
    outcome: "截圖沒有顯示之前的訊息，也未能知道有多少人看過",
    targetWord: "影射",
    targetMeaning: "不直接說出名字或事情而暗示某人",
    idealFinding: "guilty",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "公開同學姓名和分數會造成尷尬，即使沒有惡意也應先取得同意；皓文刪除和道歉，正式警告及學習私隱規則已足夠。",
  },
  {
    title: "家庭共享的耳機",
    summary: "家中共享耳機失去一邊聲音，兄妹對最後使用和充電方式各有記憶。",
    item: "白色無線耳機",
    place: "家中的書房充電座",
    time: "星期日做功課前",
    complainant: "姐姐 芷晴",
    respondent: "弟弟 朗朗",
    allegation: "他沒有把耳機放回充電座，令電池耗盡並損壞",
    reason: "他趕着上網課，把耳機留在沙發旁，之後被家人掃到地上",
    defenceAction: "他用零用錢購買替換耳塞，並和姐姐訂立共用檢查表",
    outcome: "耳機仍能充電，只有右邊耳塞接觸不良",
    targetWord: "耗盡",
    targetMeaning: "完全用完，不再剩下",
    idealFinding: "shared",
    idealPunishment: "compensation",
    idealSeverity: 2,
    idealReasoning: "朗朗沒有放回耳機是疏忽，但家人也沒有固定收納和檢查方法；他主動買替換件。按實際維修費分擔並使用檢查表較公平。",
  },
  {
    title: "回收箱的紙張",
    summary: "社區回收箱混入含油紙盒，環保隊和住戶對分類提示是否清楚有爭議。",
    item: "沾有油漬的紙盒",
    place: "屋苑地下回收站",
    time: "星期一清晨清運前",
    complainant: "環保隊員 鄧先生",
    respondent: "住戶 君怡",
    allegation: "她把不能回收的紙盒放入紙張箱，令整袋紙張需要重新檢查",
    reason: "回收箱的圖示只顯示紙盒外形，沒有說明沾油後不能回收",
    defenceAction: "她收到通知後把其他紙張重新分類，並建議管理處加上文字說明",
    outcome: "清運延遲半小時，沒有整批回收物被丟棄",
    targetWord: "分類",
    targetMeaning: "按不同特徵分開歸類",
    idealFinding: "shared",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "君怡分類時缺少清楚文字指引，環保隊也應提供例子；她願意重新整理並提出改善。提醒和更新告示比處分更適合。",
  },
  {
    title: "暴雨後的清潔工具",
    summary: "暴雨後的拖把和水桶放在逃生門前，清潔員和保安對誰應先移走工具有不同記錄。",
    item: "黃色清潔水桶和拖把",
    place: "商場地下層的逃生門旁",
    time: "黑雨警告解除後一小時",
    complainant: "保安主管 莫先生",
    respondent: "清潔員 佩儀",
    allegation: "她把工具留在逃生門前，阻礙緊急通道",
    reason: "地面仍然濕滑，她把工具放在門旁方便來回取用，打算完成最後一輪清潔後移走",
    defenceAction: "保安提醒後她立即移開工具，並在門邊放置防滑告示",
    outcome: "門仍可推開，但通道寬度比平日少了一半",
    targetWord: "阻礙",
    targetMeaning: "令事情或通道不能順利進行",
    idealFinding: "guilty",
    idealPunishment: "warning",
    idealSeverity: 1,
    idealReasoning: "逃生門前應保持暢通，佩儀把工具放在門旁仍構成風險；她即時改正且沒有造成傷害，以安全警告和清潔位置規定處理即可。",
  },
];

const gradeProfiles = {
  1: {
    targetCharacters: 170,
    episodes: 2,
    complexity: "兩個具體事件、順序清楚",
    vocabulary: "生活常用詞、簡單時間詞",
    edbFocus: "找出人物、物件及主要信息",
  },
  2: {
    targetCharacters: 240,
    episodes: 3,
    complexity: "三個具體事件、簡單因果",
    vocabulary: "常用詞、方位及原因詞",
    edbFocus: "連繫事件次序及簡單推論",
  },
  3: {
    targetCharacters: 310,
    episodes: 4,
    complexity: "四個事件、明確原因與結果",
    vocabulary: "常用詞及部分抽象詞",
    edbFocus: "事實、推論及語意理解",
  },
  4: {
    targetCharacters: 420,
    episodes: 5,
    complexity: "五個事件、多步行動及兩項成因",
    vocabulary: "連接詞、情境及抽象詞",
    edbFocus: "整合信息、理解因果及詞語",
  },
  5: {
    targetCharacters: 530,
    episodes: 6,
    complexity: "六個事件、多重原因、觀點差異及補救",
    vocabulary: "較多抽象詞及書面表達",
    edbFocus: "比較觀點、判斷證據充分程度",
  },
  6: {
    targetCharacters: 640,
    episodes: 7,
    complexity: "七個事件、交錯線索、資料限制及反事實推理",
    vocabulary: "抽象詞、條件句及正式語體",
    edbFocus: "批判閱讀、整合及以證據論證",
  },
} as const;

function chineseLength(value: string) {
  return (value.match(/[\u3400-\u4dbf\u4e00-\u9fff]/g) ?? []).length;
}

function firstPerson(value: string) {
  return value.replace(/(^|[，。；：])(?:他|她)/g, "$1我");
}

function q(
  caseId: string,
  index: number,
  construct: CaseQuestion["construct"],
  prompt: string,
  options: string[],
  answer: number,
  generalCue: string,
  specificCue: string,
  evidence: string,
): CaseQuestion {
  return {
    id: `${caseId}-q${index}`,
    construct,
    prompt,
    options,
    answer,
    generalCue,
    specificCue,
    evidence,
  };
}

function buildCase(seed: Seed, grade: 1 | 2 | 3 | 4 | 5 | 6, index: number) {
  const profile = gradeProfiles[grade];
  const id = `g${grade}-${String(index + 1).padStart(2, "0")}`;
  const caseNumber = `P${grade}-${String(index + 1).padStart(2, "0")}`;
  const respondentReason = firstPerson(seed.reason);
  const respondentAction = firstPerson(seed.defenceAction);
  const respondentAllegation = firstPerson(seed.allegation);
  const respondentName = seed.respondent.trim().split(/\s+/).at(-1) ?? seed.respondent;
  const prosecutionDetails = [
    `${seed.time}，我在${seed.place}留意到${seed.item}出了問題。按我當時所知，我認為${seed.allegation}。`,
    `我後來得知，${seed.outcome}。這個結果令我擔心同一情況會再次發生，所以我把自己記得的經過說出來。`,
    `我記得的次序是先在上述時間發現問題，然後查看${seed.item}的狀況，最後才知道造成的影響。我沒有參與${respondentName}當時的每一個決定。`,
    `就我的角度而言，問題不只是最後的結果，也包括事情發生前有沒有清楚提醒、檢查或交接。我所提出的是自己接觸過的情況，並不是轉述${respondentName}心裏的想法。`,
    `我可以直接確認的是${seed.outcome}；至於${respondentName}當時為甚麼這樣做，我沒有親耳聽到完整解釋。我是按事情的先後和物件狀況，理解為${seed.allegation}。`,
    `我也明白現場可能有我沒有留意到的因素。不過，在我發現問題的一刻，${seed.item}的狀況和原先預期不同，而這項差異確實影響了我、其他使用者或原有安排。`,
    `假如事前有人把位置、時間或處理方法說得更清楚，我相信事情可能不會發展成同樣結果。可是，對於我不在場的片段，我只能說不知道，不能把推測當成自己親眼所見。`,
    `我作出投訴，是希望交代事件對我的實際影響。即使後來有人補救，最初的問題和其後的處理仍是兩個先後相連、但不能混為一談的部分。`,
  ];
  const defenceDetails = [
    `${seed.time}，我在${seed.place}接觸過${seed.item}。當時，${respondentReason}。`,
    `${respondentAction}。我沒有打算令任何人受損，也沒有故意隱瞞自己做過的事。`,
    `我記得的次序是先遇到上述情況，之後才作出處理，最後得知${seed.outcome}。我承認結果出現了，但不同意${respondentAllegation}就是唯一解釋。`,
    `在我的角度，當時的環境和手上的資料都影響了決定。若只看最後結果，便看不到我起初為甚麼那樣做，以及發現問題後採取了甚麼行動。`,
    `我能直接交代的是自己的動機和行動：${respondentReason}。我的補救是：${respondentAction}。至於我看不見的時段發生過甚麼，我不會說自己能夠確定。`,
    `我明白別人可能把這件事理解為${seed.allegation}。我的理解則是，當時的限制、標示或突發情況先出現，才令我的行動造成沒有預計的後果。`,
    `如果當時已有更清楚的提醒、固定位置或核對程序，我會採取另一個做法。這是我事後才明白的地方，但不代表我在事發前已經知道所有風險。`,
    `我願意承認處理方法有可改善之處，也願意交代補救經過。我希望別人分清我的原意、實際行動和最後結果，而不是把三者當成同一件事。`,
  ];
  const prosecutionParagraphs: string[] = [prosecutionDetails[0]];
  const defenceParagraphs: string[] = [defenceDetails[0]];
  let prosecutionIndex = 1;
  let defenceIndex = 1;
  let allText = [...prosecutionParagraphs, ...defenceParagraphs].join("");
  while (chineseLength(allText) < profile.targetCharacters) {
    const prosecutionLength = chineseLength(prosecutionParagraphs.join(""));
    const defenceLength = chineseLength(defenceParagraphs.join(""));
    if (prosecutionLength <= defenceLength && prosecutionDetails[prosecutionIndex]) {
      prosecutionParagraphs.push(prosecutionDetails[prosecutionIndex]);
      prosecutionIndex += 1;
    } else if (defenceDetails[defenceIndex]) {
      defenceParagraphs.push(defenceDetails[defenceIndex]);
      defenceIndex += 1;
    } else if (prosecutionDetails[prosecutionIndex]) {
      prosecutionParagraphs.push(prosecutionDetails[prosecutionIndex]);
      prosecutionIndex += 1;
    } else {
      break;
    }
    allText = [...prosecutionParagraphs, ...defenceParagraphs].join("");
  }

  const optionSets = {
    factual: [
      seed.item,
      `${seed.item}的包裝或配件`,
      `另一件外觀相似、但沒有標記的物件`,
      "當日記錄中提到的另一件物品",
    ],
    inferential: [
      seed.reason,
      "他／她以為已經獲得對方同意，所以沒有再次確認",
      "他／她只想趕在限時前完成工作或離開現場",
      "另一位在場人士的說法令他／她誤會了情況",
    ],
    semantic: [
      seed.targetMeaning,
      "先把事情放在一旁，稍後才處理",
      "把物件的外表改變，令別人認不出來",
      "只描述物件的大小或顏色，沒有說明作用",
    ],
    integration: [
      `${seed.item}曾在${seed.place}出現`,
      `雙方都說${seed.item}從未離開${seed.place}`,
      "兩方都認為事情一定是故意造成，沒有其他可能",
      "雙方都看見完整的連續錄影並同意每個細節",
    ],
    evidence: [
      seed.defenceAction,
      `只聽取${seed.complainant}的猜測，沒有核對其他資料`,
      "只比較物件外觀，卻沒有查看時間或現場記錄",
      "詢問與案件無關的路人，而不查看當事人的行動",
    ],
  } as const;
  const answers = [
    (index + grade) % 4,
    (index + grade + 1) % 4,
    (index + grade + 2) % 4,
    (index + grade + 3) % 4,
    index % 4,
  ];
  const rotate = (items: readonly string[], answer: number) => {
    const correct = items[0];
    const distractors = items.slice(1);
    const result = [...distractors];
    result.splice(answer, 0, correct);
    return result;
  };
  const options = {
    factual: rotate(optionSets.factual, answers[0]),
    inferential: rotate(optionSets.inferential, answers[1]),
    semantic: rotate(optionSets.semantic, answers[2]),
    integration: rotate(optionSets.integration, answers[3]),
    evidence: rotate(optionSets.evidence, answers[4]),
  };
  const questions = [
    q(
      id,
      1,
      "factual",
      `案件中的主要物件是甚麼？`,
      options.factual,
      answers[0],
      "先找出兩篇陳詞都提到的物件。",
      `重看開頭，尋找「${seed.item}」出現的句子。`,
      seed.item,
    ),
    q(
      id,
      2,
      "inferential",
      `${seed.respondent}為甚麼會作出這個行動？`,
      options.inferential,
      answers[1],
      "分辨人物的動機和事情的結果。",
      `重看辯方第一段，留意「${seed.reason}」。`,
      seed.reason,
    ),
    q(
      id,
      3,
      "semantic",
      `文中「${seed.targetWord}」最接近以下哪個意思？`,
      options.semantic,
      answers[2],
      `把詞語放回句子，想想它描述的動作或狀態。`,
      `重看出現「${seed.targetWord}」的句子，再用自己的話替換。`,
      seed.targetWord,
    ),
    q(
      id,
      4,
      "integration",
      "雙方陳詞共同承認哪一項資料？",
      options.integration,
      answers[3],
      "比較控方和辯方各自確認的內容。",
      `兩邊都提到${seed.item}和${seed.place}，找出相同資料。`,
      `${seed.item}／${seed.place}`,
    ),
    q(
      id,
      5,
      "evidence",
      `哪項資料最能支持辯方所說的「${seed.respondent}願意補救」？`,
      options.evidence,
      answers[4],
      "選擇可以直接觀察或記錄的行動，不要只選感受。",
      `重看辯方第二段，找出事後實際做過的事情。`,
      seed.defenceAction,
    ),
  ];
  const courtCase: CourtCase = {
    id,
    caseNumber,
    title: seed.title,
    summary: seed.summary,
    grade,
    difficulty: grade,
    episodes: profile.episodes,
    complexity: profile.complexity,
    vocabulary: profile.vocabulary,
    edbFocus: profile.edbFocus,
    passages: {
      prosecution: {
        label: "控方陳詞",
        speaker: seed.complainant,
        paragraphs: prosecutionParagraphs,
      },
      defence: {
        label: "辯方陳詞",
        speaker: seed.respondent,
        paragraphs: defenceParagraphs,
      },
    },
    questions,
  };
  const ideal: IdealJudgment = {
    finding: seed.idealFinding,
    punishment: seed.idealPunishment,
    severity: seed.idealSeverity,
    reasoning: seed.idealReasoning,
  };
  return { courtCase, ideal };
}

export const expandedCaseEntries = ([1, 2, 3, 4, 5, 6] as const).flatMap(
  (grade) => seeds.map((seed, index) => buildCase(seed, grade, index)),
);

export const expandedCases: CourtCase[] = expandedCaseEntries.map(
  (entry) => entry.courtCase,
);

export const expandedIdealJudgments: Record<string, IdealJudgment> =
  Object.fromEntries(
    expandedCaseEntries.map((entry) => [entry.courtCase.id, entry.ideal]),
  );

export const casesByGrade = ([1, 2, 3, 4, 5, 6] as const).reduce(
  (result, grade) => {
    result[grade] = expandedCases.filter((courtCase) => courtCase.grade === grade);
    return result;
  },
  {} as Record<1 | 2 | 3 | 4 | 5 | 6, CourtCase[]>,
);
